//
//  Frases.swift
//  FrasesApp
//
//  Created by Dowglas Santana on 29/08/25.
//

let frasesDesmotivacionais: [String] = [
    "Desista hoje, não deixe para amanhã.",
    "Seja paciente: tudo dá errado na hora certa.",
    "Nunca é tarde demais para fracassar de novo.",
    "O importante é tentar… e falhar com estilo.",
    "A vida é feita de escolhas ruins.",
    "Não se preocupe, ninguém espera nada de você mesmo.",
    "Quanto mais você tenta, mais feio fica o tombo.",
    "Acredite nos seus sonhos… mas durma mais.",
    "Fracassar também é um talento.",
    "A motivação é passageira, o fracasso é eterno.",
    "Errar é humano, insistir é o seu destino.",
    "O que não te mata… provavelmente te deixa endividado.",
    "Não deixe para amanhã o que você pode desistir hoje.",
    "Você não é especial, apenas mais um boleto ambulante.",
    "Nunca se compare aos outros: eles sempre estarão melhores.",
    "O impossível é só uma forma elegante de dizer: ‘não dá’.",
    "Se correr o bicho pega, se ficar o bicho come. Então senta logo.",
    "Grandes conquistas exigem grandes fracassos.",
    "Não existe caminho fácil, só difícil e impossível.",
    "Seu esforço não será lembrado.",
    "Não existe limite… para a decepção.",
    "Quanto mais alto o sonho, maior o tombo.",
    "Persista até se cansar. Depois desista.",
    "Você é a prova viva de que nem todo esforço vale a pena.",
    "A cada derrota, você se aproxima de mais uma derrota.",
    "Às vezes a vida fecha uma porta… e tranca com cadeado.",
    "Nada é tão ruim que não possa piorar.",
    "Confie no processo: o processo de dar errado.",
    "A esperança é o primeiro passo para a decepção.",
    "Falhar rápido é melhor do que falhar devagar.",
    "Não importa o quanto você corra, a vida sempre chega primeiro.",
    "Seus problemas não são temporários, só aumentam com o tempo.",
    "Deus dá as batalhas mais difíceis… para você perder mesmo.",
    "Acredite: tudo pode dar errado ao mesmo tempo.",
    "O que não te destrói… vai te deixar ansioso.",
    "Cair faz parte. Ficar no chão é mais confortável.",
    "A vida é curta… e você já gastou metade reclamando.",
    "Nunca desista dos seus sonhos: apenas aceite que não vai rolar.",
    "Não há nada tão inútil quanto sua força de vontade.",
    "A estrada para o fracasso é reta e bem sinalizada.",
    "O esforço de hoje é o arrependimento de amanhã.",
    "Você nasceu para brilhar… como uma lâmpada queimada.",
    "Não é preguiça, é só o destino te poupando do fracasso.",
    "Nunca duvide: sempre dá errado no final.",
    "O sucesso é raro, o fracasso é garantido.",
    "Não é falta de sorte, é excesso de realidade.",
    "A vida sorri… mas nunca para você.",
    "Nem tudo está perdido, mas quase tudo está.",
    "O mundo gira, mas você continua parado.",
    "A realidade sempre vence a motivação.",
    "Não existe luz no fim do túnel, só mais contas.",
    "Grandes sonhos trazem grandes decepções.",
    "Levante-se, tente, e caia de novo.",
    "Seu esforço só serve para cansar você.",
    "Persistência é insistir no fracasso.",
    "Cada passo que você dá é mais longe do sucesso.",
    "Nada é tão difícil que não possa ser impossível.",
    "O impossível é só uma desculpa para não tentar… e você tem várias.",
    "Não espere nada da vida, e ainda assim vai se decepcionar.",
    "A vida não é justa, e você não é exceção.",
    "Tudo passa… até a sua paciência.",
    "Quem cedo madruga… fica com sono o dia inteiro.",
    "A sorte não bate na sua porta, ela passa direto.",
    "Quem acredita, fracassa mais confiante.",
    "Siga seus sonhos… e se perca no caminho.",
    "O amanhã pode ser pior que hoje.",
    "Não é drama, é só a sua vida mesmo.",
    "Quanto mais você planeja, mais feio será o fracasso.",
    "Você nunca é bom o bastante, mas sempre é suficiente para falhar.",
    "A vida te derruba para lembrar quem manda.",
    "Não reclame, ninguém se importa.",
    "Seja positivo: pense no lado ruim primeiro.",
    "Fracassar é apenas a prova de que você tentou à toa.",
    "A felicidade é uma mentira confortável.",
    "Um dia você vence… mas não será hoje.",
    "A cada vitória dos outros, você fica menor.",
    "Nem tudo tem solução. Na verdade, quase nada.",
    "A vida é feita de derrotas intercaladas com boletos.",
    "Seus limites são mais baixos do que você pensa.",
    "Você não está sozinho: todos fracassam também.",
    "O mundo não conspira a seu favor, ele nem liga.",
    "Não espere reconhecimento: nem você faria melhor.",
    "A montanha é alta demais e você nem começou a subir.",
    "Sonhos não se realizam, eles viram frustrações.",
    "Sempre existe um jeito pior de dar errado.",
    "Nunca é cedo demais para desistir.",
    "As coisas boas acabam, as ruins ficam.",
    "Sua zona de conforto é o seu lar eterno.",
    "A vida não ensina, só humilha.",
    "Não é azar, é só incompetência mesmo.",
    "Cada conquista que você imagina é só um delírio.",
    "Não existe caminho certo, só errado e mais errado.",
    "Quem ri por último provavelmente não entendeu nada.",
    "Você não chegou no fundo do poço, ainda tem escada para descer.",
    "Seus erros são apenas treino para os próximos erros.",
    "A vida não dá limões, ela joga pedras.",
    "Seus sonhos não estão mortos, só nunca nasceram.",
    "O sucesso alheio é só para te lembrar do fracasso próprio.",
    "Estudar é ótimo… para descobrir o quanto você não sabe.",
    "Se você não entende, relaxa: vai continuar não entendendo.",
    "Cada página lida é mais uma prova de que o livro é difícil demais.",
    "A única coisa que cresce com o tempo é a pilha de matérias atrasadas.",
    "Se o plano era aprender rápido, parabéns: já falhou.",
    "Estudar hoje só garante a mesma dúvida amanhã.",
    "A revisão serve para mostrar que você esqueceu tudo.",
    "Quem nunca decorou sem entender, que atire a primeira apostila.",
    "A cada resumo feito, nasce mais um capítulo não lido.",
    "O conteúdo é grande e sua paciência é pequena.",
    "O maior inimigo do estudante não é a prova, é a própria motivação.",
    "Sua memória é excelente… para coisas inúteis.",
    "Quanto mais você finge que entende, mais convincente fica o fracasso.",
    "A matéria não é difícil, você é que não nasceu para isso.",
    "Estudar de madrugada só serve para aprender a dormir em pé.",
    "Você até começa animado… mas logo lembra quem você é.",
    "Quanto mais você estuda, mais percebe que sabe nada.",
    "Seu maior talento é acumular conteúdo atrasado.",
    "O professor explica, você não entende, e a vida segue.",
    "Estudar é acumular dúvidas com método."
]

